  <?php echo $this->getContent(); ?>

<!--img src="data:image/jpg;base64, echo base64_encode($this->session->get('user')['Foto'])"/-->

  <div class="container">
    <!-- Menu responsivo -->
    <ul id="slide-out" class="sidenav">
      <li>
        <div class="user-view">
          <div class="background">
            <img src="https://i.ibb.co/JFVv2m5/ey29-Qkq-jpg.png" class="">
          </div>
          <div style="margin-bottom: 20px;">
            <a href="<?php echo $this->url->get('usermanage/index')?>">
              <?php
                if ($this->session->get('userFoto')!=null) {
                  ?>
                  <img class="circle" src="data:image/jpg;base64,<?php echo base64_encode($this->session->get('userFoto'))?>">
                  
                  <?php
                }
                else{
                  ?>
                  <img class="circle responsive-img" src="https://www.stickpng.com/assets/images/585e4beacb11b227491c3399.png">
                  <?php
                }
              ?>  
              
            </a>
            
          </div>
          <div>
            <p class="p_sidenav"><?php echo $this->session->get('user')['Nombre'] ?> - <?php echo $this->session->get('user')['Matricula'] ?></p>
            <p class="p_sidenav"><?php echo $this->session->get('user')['Correo'] ?></p>
          </div>
        </div>
      </li>


      <!--li><a class="subheader"></a></li-->
      <li style="margin-top:15px">
        <?php
        $id_grupo_aux = null;
        //si esta definido el id de grupo actual se manda para guardar en HISTORIAL (user logout)
        if ($this->session->has('Id_Grupo_Actual')) $id_grupo_aux = $this->session->get('Id_Grupo_Actual');


        
        echo $this->tag->linkTo("grupo/desconectarGrupo/?id_grupo=$id_grupo_aux", "<i class=\"material-icons text-grey\">home</i>Inicio");
          //linkTo("grupo/desplegarGrupo/?id_grupo=$grupo->Id_Grupo &tipo=1", '<i class="material-icons">donut_large</i> Abrir')
        ?>
        
      </li>
      <li>
        <div class="divider"></div>
      </li>
      <li><a class="subheader">Grupos</a></li>
      <li><a href="#modal1" class="modal-trigger"><i class="material-icons" style="color: #7cb342">add</i>Crear</a></li>
      <li><a href="#modal2" class="modal-trigger"><i class="material-icons" style="color: #ffa726">device_hub</i>Unirse</a></li>
      <!--<li><a href="#modal3" class="modal-trigger"><i class="material-icons" style="color: #e65100">delete</i>Eliminar</a></li>-->
      <li>
        <div class="divider"></div>
      </li>
      <li><a class="subheader">Mis Grupos</a></li>
      <?php if ($grupos->count() > 0) { ?>
          <ul id='dropdown1' class='mainmenu'>
            <?php foreach ($grupos as $grupo) { ?>
              <li>
                <div class="row">
                  <div class="col s11 m11 l11" >
                    <?php echo $this->tag->linkTo("grupo/desplegarGrupo/?id_grupo=$grupo->Id_Grupo &tipo=1", $grupo->Nombre_G) ?> 
                  </div>
                  <div class="col s1 m1 l1" style="margin-left: -30px">
                    <?php echo $this->tag->linkTo("grupo/desplegarGrupo/?id_grupo=$grupo->Id_Grupo &tipo=2", '<i class="material-icons" style="color: #263238">build</i>') ?>  
                  </div>
                </div>
              </li>
            <?php } ?>
          </ul>
        </li>
      <?php } else { ?>
        <li align="center">Aquí se mostrarán tus grupos</li>
      <?php } ?>
      <li>
        <div class="divider"></div>
      </li>
      <li><a class="subheader">Salir</a></li>
      <li>
        <?php
        echo $this->tag->linkTo("grupo/logout", "<i class=\"material-icons\" style=\"color: #e53935\">clear</i>Cerrar Sesión");
        ?>
      </li>
    </ul>
    <a href="#" data-target="slide-out" class="sidenav-trigger"><i id="icon_menu" class="small material-icons grey-text text-darken-1">clear_all</i></a>

  </div>

  <!--Crear grupo nuevo-->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="row">
      <div class="modal-content col s12 m6 ">
        <h4 class="center espaciado_up_down_m">Crear nuevo grupo</h4>
        <p class="center color_p espaciado_up_down_m">Hola <?php echo $this->session->get('user')['Nombre'] ?>, por favor completa los campos solicitados para crear un nuevo grupo</p>

        <?= $this->tag->form(['name' => 'add_group', "grupo/crearGrupo"]); ?>
        <div class="col s12 m4 espaciado_up_down_m center">
          <i class="material-icons large" style="color: #7cb342">add</i>
        </div>

        <div class="col s12 m8">
          <div class="col m12 s12">
            <div class="input-field">
              <?= $this->tag->textfield(['name_group', 'name' => 'name_group', 'class' => 'validate']); ?>
              <label for="name_group">Nombre del grupo</label>
            </div>
          </div>

          <div class="col s12 m12">

            <div class="input-field">
              <?= $this->tag->textfield(['clave_group', 'name' => 'clave_group', 'class' => 'validate']); ?>
              <label for="clave_group">Clave del grupo</label>
            </div>

            <!--<div class="chips chips-placeholder chips-initial input-field" id="chipsArrayId">
             <input class="chips-placeholder" onkeypress="return checar(event)">
           </div>-->
          </div>

          <br>
        </div>
        <div class="class s12 m12 l12">
          <p class="color_p center espaciado_up_down_m">Nota: El grupo solo contendrá a un integrante, el cual es usted, para que más personas puedan acceder al grupo,
            comparta la clave con los usuarios que desee.</p>
          <p class="color_p center">Ingresando en la seccion "Unirse" usted podrá acceder a nuevos grupos</p>
        </div>
        <span class="helper-text" id="span1" style="color:red;"></span>
      </div>

      <!--input type="hidden" id="arrayChipPostId" name="arrayChipPost" value=""-->
      <div class="modal-footer">
        <div class="center">
          <button id="id_boton_chips" class="waves-effect waves-green btn-flat" type="submit" name="action" onclick="return validate('add_group',['name_group'], 'span1')">Crear</button>
          <a href="#!" class="modal-close waves-effect waves-red btn-flat">Cancelar</a>
        </div>

      </div>
      <?= $this->tag->endform(); ?>
    </div>
  </div>

  <!--Unirse a grupo-->
  <div id="modal2" class="modal modal-fixed-footer">
    <div class="row">
      <div class="modal-content col s12 m6">
        <h4 class="center espaciado_up_down_m">Unirse al grupo</h4>
        <p class="color_p center espaciado_up_down_m">Por favor completa los campos solicitados para unirte a algún grupo</p>
        <div class="col s12 m12 l12 center"><i class="material-icons medium" style="color: #ffa726">device_hub</i></div>
        <?= $this->tag->form(['name' => 'join_to_group', "grupo/unirseGrupo"]); ?>

        <div class="col s12 m12 l12 center">
          <div class="col offset-m3 m6 s12">
            <select id="id_group" name="id_group_name">
              <option value="" disabled selected>Elije un grupo</option>
              <?php
              if (isset($gruposComp)) {
                foreach ($gruposComp as $grupo) {
                  ?>
                  <option value="<?php echo $grupo->Id_Grupo ?>"><?php echo $grupo->Nombre_G; ?></option>
                <?php
                  }
                  ?>
              <?php
              } else {
                ?>
                <option value="" disabled selected>No hay grupos que mostrar para unirse</option>
              <?php
              }
              ?>
            </select>
            <label>Materialize Select</label>
          </div>
          <div class="col offset-m3 m6 s12">
            <div class="input-field"><?= $this->tag->passwordfield(['cl_group', 'name' => 'cl_group', 'class' => 'validate']); ?>
              <label for="cl_group">Clave del grupo</label>
            </div>
          </div>
        </div>
        <div class="row center">
          <span class="helper-text" id="span2" style="color:red;"></span>
        </div>

      </div>

      <div class="modal-footer">
        <div class="center">
          <button class="waves-effect waves-green btn-flat" type="submit" name="action" onclick="return validate('join_to_group',['id_group','cl_group'], 'span2')">Unirme</button>
          <a href="#!" class="modal-close waves-effect waves-red btn-flat">Cancelar</a>
        </div>

      </div>
      <?= $this->tag->endform(); ?>
    </div>
  </div>

  <?php
  if (!$this->session->has('Tipo_Despli')) {
    ?>
    <!--Pantalla de bienvenida-->
    <div class="row" id="view_ini">
      <div class="col s12 m12 l12 center">
        <img id="img_ini" src="https://i.ibb.co/NVN2rSG/networking-1.png" width="256" height="256">
        <h4 id="Title">Colaborative</h4>
      </div>
      <div class="col s12 m12 l12 center">
        <h2>¡Bienvenido, <?php echo $this->session->get('user')['Nombre'] ?>!</h2>
      </div>

      <div class="col s12 m12 l12 center">
        <div class="container">
          <ol type="A">
            <li type="disc" id="p_1">Colaborative es una aplicación que te permite estar conectado con personas como !tu!.</li>
            <li type="disc" id="p_2">Utíliza Colaborative como más te guste</li>
            <li type="disc" id="p_3"> Comparte archivos, artículos, fotos, proyectos.</li>
            <li type="disc" id="p_4">Comienza eligiendo tu grupo de trabajo</li>
          </ol>
        </div>
      </div>
    </div>
    <?php
    } else {
      if (isset($infoGrupo)) {
        //Se crea un arreglo de avatares para imágenes random en users
        $avatar = array(
          "https://i.ibb.co/3WxvDCf/boy.png", "https://i.ibb.co/PFthpPT/boy-1.png", "https://i.ibb.co/KjNNY64/girl.png", "https://i.ibb.co/tsytp0V/girl-1.png",
          "https://i.ibb.co/p2G5vJ3/man.png", "https://i.ibb.co/T0hn4Qg/man-1.png", "https://i.ibb.co/5sJgMm3/man-2.png", "https://i.ibb.co/r4W8m4Y/man-3.png",
          "https://i.ibb.co/YT0Y6Ws/man-4.png"
        );
        switch ($this->session->get('Tipo_Despli')) {
          case '1': //se despliega Abrir grupo (Con chats)
            ?>
          <div class="row view_group">
            <div class="col s12 m12 l12 center">
              <h5><?php echo $infoGrupo->Nombre_G; ?></h5>
            </div>

            <div class="col offset-l8 m12 s12 l4 center">
              <ul>
                <li id="p_5" class="tooltipped hand" data-position="bottom" data-tooltip="<?php echo "Id Grupo: " . $infoGrupo->Id_Grupo . "<br>" . "Clave: " . $infoGrupo->Clave_Grupo; ?> ">Informacion del grupo <i class="material-icons tiny">expand_more</i></li>
              </ul>

            </div>

            <div class="col s12 m12 l12 center">
              <p id="p_6">Integrantes: </p>
              <?php
                    foreach ($miembros as $miembro) {
                      $get_position = random_int(0, 8);
                      ?>
                <div class="chip" style="margin-top: 10px">
                  <img class="tooltipped hand" data-position="bottom" data-tooltip="<?php echo $miembro['Correo']; ?>" src='<?php echo $avatar[$get_position]; ?>' height="32" width="32">
                  <?php echo $miembro['Nombre']; ?>
                </div>
              <?php } ?>

              <div class="row">
                <div class="center col s12 m8 l8 offset-m2 offset-l2 grey-text text-darken-1">
                  "Coperative" te permite navegar sobre las bibliotecas virtuales más conocidas, para poder recuperar y compartir artículos científicos o cualquier documento que desees sin salir de tu aplicación favorita. La mejor manera de trabajar Colaborativamente!
                </div>
              </div>
            </div>

            
            
            
          </div>
          <script type="text/javascript">
            var instance = M.Tabs.init(el);
          </script>

          <div class="row container">
            <div class="col s12">
              <ul class="tabs">
                <li class="tab col s3"><a href="#test1" class="active">Principal</a></li>
                <li class="tab col s3"><a  href="#test2">Actividad del grupo</a></li>
              </ul>
            </div>
            <div id="test1" class="col s12">
              <div class="row">
              <div class="col s12 m6 l6">
                <div class="row">
                  <div class="col s12 m6 l6">
                    <select id="id_filtro_biblio" name="biblioteca_name" onchange="cambiarBiblioteca()">
                      <option value="" disabled selected>Elije una biblioteca</option>
                      <option value="1">ACM</option>
                      <option value="2">IEEE</option>
                      <option value="3">Emerald Insight</option>
                      <option value="4">EMIS Intelligence</option>
                      <option value="5">Nature</option>
                      <option value="6">ACS</option>

                      <option value="7">Springer</option>
                      <option value="8">Tylor & Francis</option>
                      <option value="9">AMS</option>
                      <option value="10">Wiley Online Library</option>
                    </select>
                    <label>Materialize Select</label>
                  </div>
                  <div class="col s12 m12 l12">
                    <iframe id="id_iFrame" src="" width="100%" height="400px"></iframe>
                  </div>
                </div>
              </div>
              <div class="col s12 m5 l5">
                <div class="row">
                  <div  id="id_biblio_div" style="display: none;">
                    
                      <a class="left btn-floating btn-large white pulse">
                          <!--img src="<?php echo $this->url->get('img/bibliotecas/ieee.png')?>" width="50px" height="50px"-->
                          <img src="" id="id_biblio_icon" width="50px" height="50px">
                      </a>
                      <div class="chip" id="id_biblio_text" style="font-size: 16px; margin-top: 12px; margin-left: 7px;">
                        <!-- Está navegando por: IEEE<-->
                      </div>
                    
                    
                  </div>
                </div>
                <div class="row">
                  <div id="Id_Caja_Grande" class="col s12 m12 l12 card">
                    <ul id="div_chat">
                      <!--Aqui van los mensajes del Chat-->
                    </ul>
                  </div>
                </div>
                <div class="row"></div>
                <div class="row">
                  <div class="col s12 m12 l12" id="card_1">
                    <div class="row" id="Id_Mensaje_Field">
                      <div class="input-field col s11 m11 l11 center">
                        <?php echo $this->tag->textArea(['id_mensaje', 'name' => 'mensaje_name', 'required' => 'required', 'onkeypress' => "return checarEnterMensaje(event)", 'class' => 'materialize-textarea']); ?>
                        <label for="id_mensaje">Escribe un mensaje</label>
                      </div>
                      <div class="col s1 m1 l1">
                        <div class="row">
                          <button id="id_boton_mensaje" class="boton col s12 m12 l12 waves-effect  waves-light btn-small prefix" name="action">
                            <i class="material-icons yellow-text text-lighten-5">send</i>
                          </button>
                        </div>
                      </div>
                    </div>
                    <!--Adjuntar Foto-->
                    <div class="row" id="Id_Foto_Field" style="display: none;">
                      <form enctype="multipart/form-data" id="formuFotoAjax" method="post">
                        <div class="col s10 m10 l10">
                          <div class="file-field input-field">
                            <div class="btn blue">
                              <span>Seleccionar</span>
                              <input id="id_foto" type="file" name="Nombre_Img" value="fichero">
                            </div>
                            <div class="file-path-wrapper">
                              <input id="id_path_foto" class="file-path" placeholder="Selecciona una imagen" readonly="readonly" type="text">
                            </div>
                          </div>
                        </div>

                        <a href=# class="col s1 m1 l1" onClick="borrarFotoField()"><i class="tiny material-icons white red-text text-darken-1">cancel</i></a>

                        <div class="col s1 m1 l1">
                          <div class="row">
                            <button id="id_boton_foto" type="submit" class="boton col s12 m12 l12 waves-effect  waves-light btn-small" name="action">
                              <i class="material-icons yellow-text text-lighten-5">send</i>
                            </button>
                          </div>
                        </div>
                        <div class="col s12 m12 l12 center" id="id_error_img">
                          <!--Aqui van los errores de las img's-->
                        </div>
                      </form>
                    </div>

                    <!--Adjuntar Documento-->

                    <div class="row" id="Id_Doc_Field" style="display: none;">
                      <form enctype="multipart/form-data" id="formuDocAjax" method="post">
                        <div class="col s10 m10 l10">


                          <div class="file-field input-field">
                            <div class="btn green">
                              <span>Seleccionar</span>
                              <input id="id_doc" type="file" name="Nombre_File" value="fichero">
                            </div>
                            <div class="file-path-wrapper">
                              <input id="id_path_doc" class="file-path" placeholder="Selecciona un documento" readonly="readonly" type="text">
                            </div>
                          </div>
                        </div>

                        <a href=# class="col s1 m1 l1 white" style="border: 0px;" onclick="return borrarDocField()"><i class="tiny material-icons white red-text text-darken-1" style="">cancel</i></a>
                        <div class="col s1 m1 l1">
                          <div class="row">
                            <button id="id_boton_doc" class="boton col s12 m12 l12 waves-effect  waves-light btn-small prefix" name="action">
                              <i class="material-icons yellow-text text-lighten-5">send</i>
                            </button>
                            <!--a class="waves-effect waves-light btn-small prefix" id="boton"><i class="material-icons">send</i></a-->
                          </div>
                        </div>
                        <div class="col s10 m10 l10 center" id="id_error_doc">
                          <!--Aqui van los errores de los doc's-->
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                  
              </div>
          </div>
            </div>
            <div id="test2" class="col s12">
              <div class="row">
                <div id="cajaGrande2" class="col s12 m12 l8 offset-l2 center card">
                  <!--<button id="id_boton_history" class="waves-effect waves-light btn modal-trigger center" -href="#modal_ac">Actividad de grupo</button> -->

                  <!-- Modal Structure -->
                  <div id="modal_ac">
                    <div id="id_history_Caja_Grande">
                      <h4>Actividad del grupo</h4>
                      <div class="divider"></div>
                      <div id="id_history_content" align="left">
                        <!--Aqui va el historial de cada grupo-->               
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>


          </div>

          

          

          <div class="fixed-action-btn">
            <a class="btn-floating btn-large red">
              <i class="large material-icons">add</i>
            </a>
            <ul>
              <li>
                <button class="btn-floating blue btn tooltipped" data-position="left" data-tooltip="Comparte una imagen" onclick="return adjuntarFileImg()">
                  <i class="material-icons">image</i>
                </button>
              </li>
              <li>
                <button class="btn-floating green btn tooltipped" data-position="left" data-tooltip="Comparte un documento" onclick="return adjuntarFileDoc()"><i class="material-icons">attach_file</i>
                </button>
              </li>
            </ul>
          </div>
        <?php
              break;

            case '2': //se despliega Administración de grupo (Líder)
              ?>
          <!-- Vista para administrador de grupo (Líder)-->
          <div class="row">
            <h4 class="center espaciado_up_down"> Administración grupo: <?php echo $infoGrupo->Nombre_G; ?> (Líder)</h4>
            <div class="col s12 m12 l12">
              <?= $this->tag->form(['name' => 'conf_group', "grupo/Grupo_Conf", 'onsubmit' => "return confirmacionGuardar()"]); ?>
              <p class="center espaciado_up_down color_p">Hola <?php echo $this->session->get('user')['Nombre'] ?>, aquí podrás administrar todo lo relacionado a tu grupo</p>

              <?php echo (isset($Result_Gestion['Sin_Cambio'])) ? $Result_Gestion['Sin_Cambio'] : ""; ?>

              <div class="row">
                <div class="col s12 m12 l6 offset-l3 input-field">
                  <br>
                  <!--Campo oculto para guardar el nombre anterior del grupo-->
                  <?= $this->tag->textfield(['id_name_G_ant', 'name' => 'nombreG_anterior', 'value' => $infoGrupo->Nombre_G, 'style' => 'display:none']); ?>
                  <?= $this->tag->textfield(['id_name_G', 'name' => 'nombreG', 'class' => 'validate', 'value' => $infoGrupo->Nombre_G]); ?>
                  <label for="id_name_G">Nombre del grupo</label>

                  <?php echo (isset($Result_Gestion['Cambio_Nombre'])) ? $Result_Gestion['Cambio_Nombre'] : ""; ?>
                </div>

                <div class="col s12 m12 l12 center espaciado_up_down">
                  <p class="color_p_ti">Integrantes: </p>
                  <div id="ChipsPadre">
                    <?php
                          foreach ($miembros as $miembro) {
                            $get_position = random_int(0, 8);
                            ?>
                      <div class="chip" style="margin-top: 10px">
                        <div class="chipMatricula" style="display: none;"><?php echo $miembro['Matricula'] ?></div>
                        <img class="tooltipped hand" data-position="bottom" data-tooltip="<?php echo $miembro['Correo']; ?>" src='<?php echo $avatar[$get_position]; ?>' height="32" width="32">
                        <?php echo $miembro['Nombre']; ?>
                        <!--Si es la matricula del lider no se pone la "X" para ser borrado-->
                        <?php if ($miembro['Matricula'] != $this->session->get('user')['Matricula']) { ?>
                          <i class="close material-icons">close</i>
                        <?php } ?>

                      </div>
                    <?php } ?>
                  </div>
                  <div class="chips" id="id_chipsField" style="display: none;">
                  </div>
                  <input type="hidden" id="arrayChipPostId_Ant" name="arrayChipPost_Ant" value="">
                  <input type="hidden" id="arrayChipPostId" name="arrayChipPost" value="">
                  <?php echo $this->tag->textfield(['id_grupo_actual', 'name' => 'id_grupo', 'style' => 'display:none', 'value' => $this->session->get('Id_Grupo_Actual')]); ?>
                  <?php echo (isset($Result_Gestion['Cambio_Chips'])) ? $Result_Gestion['Cambio_Chips'] : ""; ?>
                </div>
                <!------Forma de recuperar los id de los integrantes---->
                <script type="text/javascript">
                  $('.chips').chips();

                  var miembros = <?php echo json_encode($miembros); ?>;
                  var instance = M.Chips.getInstance($('#id_chipsField'));

                  for (var i = 0; i < miembros.length; i++) {
                    instance.addChip({
                      tag: miembros[i].Matricula
                    });
                  }

                  document.getElementById("arrayChipPostId_Ant").value = JSON.stringify(instance.chipsData);
                </script>
                <!------------------------->

                <div class="col s12 m12 l6 offset-l3 input-field center espaciado_up_down">
                  <br>
                  <?= $this->tag->textfield(['id_clave_ant', 'name' => 'claveAnterior', 'value' => $infoGrupo->Clave_Grupo, 'style' => 'display:none']); ?>
                  <?= $this->tag->textfield(['id_clave_G', 'name' => 'claveG', 'class' => 'validate', 'value' => $infoGrupo->Clave_Grupo]); ?>
                  <label for="id_clave_G">Clave del grupo</label>
                  <?php echo (isset($Result_Gestion['Cambio_Clave'])) ? $Result_Gestion['Cambio_Clave'] : ""; ?>
                </div>


                <div class="col s12 m12 l12 center espaciado_up_down">
                  <button class="button_admin_save green lighten-1 white-text" type="submit" name="action" onclick="recuperarChipInfo()">Guardar</button>
                  <?= $this->tag->endform(); ?>

                  <?php echo $this->tag->form(['name' => 'delete_group', "grupo/eliminarGrupo", 'onsubmit' => "return confirmacion()"]);

                        echo $this->tag->textfield(['id_grupo_actual', 'name' => 'id_grupo_actual', 'style' => 'display:none', 'value' => $this->session->get('Id_Grupo_Actual')]);

                        ?>
                  <div class="col2 s1 m12 l12">
                    <button class=" button_admin_elim red lighten-1 white-text" type="submit" name="action">Eliminar grupo</button>
                  </div>
                  <?= $this->tag->endform(); ?>
                </div>
              </div>

            </div>
          </div>
          <!--hr-->
        <?php
              break;
            case '3': //se despliega Administración de grupo (Integrante)
              ?>
          <!--Vista del usuario del grupo-->
          <div class="row">
            <h4 class="center espaciado_up_down"> Administración grupo: <?php echo $infoGrupo->Nombre_G; ?> (Integrante)</h4>
            <div class="col s12 m12 l12">
              <?= $this->tag->form(['name' => 'conf_group', "grupo/dejarGrupoIntegrante", 'onsubmit' => "return confirmacion_user()"]); ?>
              <p class="center espaciado_up_down color_p">Hola <?php echo $this->session->get('user')['Nombre'] ?>, como te habrás dado cuenta las funciones que tienes son limitadas, para más informacion comunicate con el administrador del grupo</p>
              <div class="row">
                <div class="col s12 m12 l6 offset-l3 center">
                  <br>
                  <p class="color_p_ti">Nombre del grupo</p>
                  <span class="span_info"><?php echo $infoGrupo->Nombre_G; ?></span>
                </div>

                <div class="col s12 m12 l12 center">
                  <p class="color_p_ti espaciado_up_down">Integrantes: </p>
                  <?php

                        foreach ($miembros as $miembro) {
                          $get_position = random_int(0, 8);
                          ?>
                    <div class="chip" style="margin-top: 10px">
                      <img class="tooltipped hand" data-position="bottom" data-tooltip="<?php echo $miembro['Correo']; ?>" src='<?php echo $avatar[$get_position]; ?>' height="32" width="32">
                      <?php echo $miembro['Nombre']; ?>
                    </div>
                  <?php } ?>
                </div>

                <div class="col s12 m12 l6 offset-l3 center">
                  <p class="color_p_ti center espaciado_up_down">Clave del grupo</p>
                  <span class="span_info"><?php echo $infoGrupo->Clave_Grupo; ?></span>
                </div>



                <div class="center">
                  <div class="col s12 m12 l12 espaciado_up_down center">
                    <button class=" button_admin_elim red lighten-1 white-text " type="submit" name="action">Salir del grupo</button>
                  </div>
                </div>


              </div>

              <?= $this->tag->endform(); ?>
            </div>
          </div>
        <?php
              break;
            default:
              echo "El tipo no tiene valor válido, Error";
              break;
          }
        } else {
          ?>
        <div class="row" id="view_ini">
          <div class="col s12 m12 l12 center">
            <img id="img_ini" src="https://i.ibb.co/NVN2rSG/networking-1.png" width="256" height="256">
            <h4 id="Title">Colaborative</h4>
          </div>
          <div class="col s12 m12 l12 center">
            <h2>¡Bienvenido, <?php echo $this->session->get('user')['Nombre'] ?>!</h2>
          </div>

          <div class="col s12 m12 l12 center">
            <div class="container">
              <ol type="A">
                <li type="disc" id="p_1">Colaborative es una aplicación que te permite estar conectado con personas como !tu!.</li>
                <li type="disc" id="p_2">Utíliza Colaborative como más te guste</li>
                <li type="disc" id="p_3"> Comparte archivos, artículos, fotos, proyectos.</li>
                <li type="disc" id="p_4">Comienza eligiendo tu grupo de trabajo</li>
              </ol>
            </div>
          </div>
        </div>

    <?php
      }
    }
    ?>

    <script type="text/javascript">
      M.AutoInit();
      $('.chips').chips();
    </script>

    <script type="text/javascript">
      function adjuntarFileImg() {
        document.getElementById('id_foto').click();
        document.getElementById('id_path_foto').value = "";
        document.getElementById('id_error_img').textContent = "";
        document.getElementById('id_error_doc').textContent = "";
        document.getElementById('Id_Foto_Field').style.display = 'block';
        document.getElementById('Id_Doc_Field').style.display = 'none';
        document.getElementById('Id_Mensaje_Field').style.display = 'none';
      }

      function adjuntarFileDoc() {
        document.getElementById('id_doc').click();
        document.getElementById('id_path_doc').value = "";
        document.getElementById('id_error_img').textContent = "";
        document.getElementById('id_error_doc').textContent = "";
        document.getElementById('Id_Doc_Field').style.display = 'block';
        document.getElementById('Id_Foto_Field').style.display = 'none';
        document.getElementById('Id_Mensaje_Field').style.display = 'none';
      }

      function borrarFotoField() {
        document.getElementById('id_path_foto').value = "";
        document.getElementById('id_error_img').textContent = "";
        document.getElementById('Id_Foto_Field').style.display = 'none';
        document.getElementById('Id_Mensaje_Field').style.display = 'block';
      }

      function borrarDocField() {
        document.getElementById('id_path_doc').value = "";
        document.getElementById('id_error_doc').textContent = "";
        document.getElementById('Id_Doc_Field').style.display = 'none';
        document.getElementById('Id_Mensaje_Field').style.display = 'block';
      }
    </script>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems);
      });
    </script>

    <script type="text/javascript">
      var numHistory = 0;
      function ajaxFuncion2(){
        $.ajax({
                url: "<?php echo $this->url->get('Grupo/getHistoryAjax'); ?>",
                type: 'GET',
                dataType: 'json',
                data: {}
              }).done(function(data) {
                var sizeApend = 0;
                if(!((typeof data) == "string"))
                { 
                  if (data.length < numHistory) { 
                    //reinicio por DB comprometida
                    document.getElementById("id_history_content").textContent = "";
                    sizeApend = data.length;
                  }
                  else if (data.length > numHistory) {
                    //Apendizar historial restante
                    sizeApend = data.length - numHistory;
                  }

                  var divHistory = document.getElementById("id_history_content");
                  for(var i=numHistory,k=0;k<sizeApend; i++,k++){
                    //console.log("for history: i = "+i);
                    var auxP = document.createElement('p');
                    switch(data[i].Tipo_H){
                      case '0':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" se desconectó";
                      break;
                      case '1':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" se conectó";
                      break;
                      case '2':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" compartió una imagen al grupo";
                      break;
                      case '3':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" compartió un documento al grupo";
                      break;
                      case '4':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" cambió el nombre del grupo";
                      break;
                      case '5':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" cambió la contraseña del grupo";
                      break;
                      case '6':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" eliminó a alguien del grupo";
                      break;
                      case '7':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" se ha unido al grupo";
                      break;
                      case '8':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" ha salido del grupo";
                      break;
                      case '9':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" creó el grupo";
                      break;

                      case '10':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" compartió un enlace en el grupo";
                      break;
                      case '12':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" navegó por la biblioteca: "+data[i].Biblioteca;
                      break;

                      default: auxP.textContent = "Mensaje Dafault";
                    }
                    divHistory.appendChild(auxP);
                  }

                  numHistory = data.length;
                }
                else{
                  //alert(data);
                }

                

                //var cajaHistory = document.getElementById('id_history_content');
                //if (globalScrollTopHistory != cajaHistory.scrollHeight) {
                //  document.getElementById('id_history_content').scrollTop = cajaHistory.scrollHeight;
                //  globalScrollTopHistory = cajaHistory.scrollHeight;
                //}

                //console.log("Se esta ejecutando tarea de historial");
              });
      }

      window.setInterval(function() {
        ajaxFuncion2();
      }, 2500);
    </script>
    <script type="text/javascript">
      var numMensaje = 0;

      function ajaxFuncion() {

        $.ajax({
          url: "<?php echo $this->url->get('Grupo/cargarMensajes'); ?>",
          type: 'GET',
          dataType: 'json',
          data: {
            id_grupo: <?php echo ($this->session->has('Id_Grupo_Actual')) ? $this->session->get('Id_Grupo_Actual') : 0 ?>
          }
        }).done(function(data) {

          if (!((typeof data) == "string")) {
            var chat_Caja = document.getElementById("div_chat");
            if (chat_Caja != null) {
              var sizeApend = 0;
              if (data.length < numMensaje) { 
                //reinicio por DB comprometida
                chat_Caja.textContent = "";
                sizeApend = data.length;
              }
              else if (data.length > numMensaje) {
                //Apendizar historial restante
                sizeApend = data.length - numMensaje;
              }
              
              for (var i=numMensaje,k=0;k<sizeApend; i++,k++) {
                //console.log("for mensajes: i = "+i);
                var newLi = document.createElement("li");
                var newDiv1 = document.createElement("div");
                newDiv1.className = "row";
                var newDiv1_1 = document.createElement("div");
                var newDiv1_2 = document.createElement("div");
                var newDiv1_2_1 = document.createElement("div");
                var newDiv1_2_2 = document.createElement("div");
                var newDiv1_2_3 = document.createElement("div");

                var imgAux = document.createElement("img");
                imgAux.src = '<?php echo $avatar[random_int(0, 8)]; ?>';
                imgAux.height = '32';
                imgAux.width = '32';
                imgAux.alt = 'Contact Person';

                if (data[i].Matricula == <?php echo $this->session->get('user')['Matricula']; ?>) {

                  newDiv1_1.className = "col s2 m2 l2";
                  newDiv1_1.appendChild(imgAux);

                  newDiv1_2.className = 'col s10 m10 l10';
                  newDiv1_2_1.className = "row right blue-grey-text text-lighten-2";
                  newDiv1_2_1.textContent = "Yo";
                  newDiv1_2_2.className = "row grey-text text-darken-2 div_back";
                  newDiv1_2_2.style.marginBottom = "-10px";
                  newDiv1_2_2.style.marginTop = "30px";


                  switch (data[i].Tipo_M) {
                    case '0':
                      newDiv1_2_2.innerHTML = data[i].Mensaje;
                      break;
                    case '1':
                      var auxImgMessage = document.createElement('img');
                      auxImgMessage.src = data[i].Mensaje;
                      auxImgMessage.height = "200";
                      auxImgMessage.width = "200";
                      newDiv1_2_2.appendChild(auxImgMessage);
                      break;
                    case '2':
                      var aAux = document.createElement('a');
                      aAux.href = data[i].Mensaje;
                      aAux.target = "_blank";
                      aAux.textContent = data[i].Mensaje.replace(/((\/[_a-zA-Z0-9]+){0,}\/)([a-zA-Z0-9\s\.ñ\(\)]+)/, '$3');

                      newDiv1_2_2.appendChild(aAux);
                      break;

                    default:
                  }




                  newDiv1_2_3.className = "row right blue-grey-text text-lighten-2";
                  newDiv1_2_3.textContent = data[i].Hora;
                  newDiv1_2.appendChild(newDiv1_2_1);
                  newDiv1_2.appendChild(newDiv1_2_2);
                  newDiv1_2.appendChild(newDiv1_2_3);
                } else {
                  newDiv1_2.className = "col s2 m2 l2";
                  newDiv1_2.appendChild(imgAux);

                  newDiv1_1.className = 'col s8 m8 l8';
                  newDiv1_2_1.className = "row blue-grey-text text-lighten-2";
                  newDiv1_2_1.textContent = data[i].Nombre;
                  newDiv1_2_2.className = "row grey-text text-darken-2 div_back";
                  newDiv1_2_2.style.marginBottom = "-10px";
                  newDiv1_2_2.style.marginTop = "-6px";


                  switch (data[i].Tipo_M) {
                    case '0':
                      newDiv1_2_2.innerHTML = data[i].Mensaje;
                      break;
                    case '1':
                      var auxImgMessage = document.createElement('img');
                      auxImgMessage.src = data[i].Mensaje;
                      auxImgMessage.height = "200";
                      auxImgMessage.width = "200";
                      newDiv1_2_2.appendChild(auxImgMessage);
                      break;
                    case '2':
                      var aAux = document.createElement('a');
                      aAux.href = data[i].Mensaje;
                      aAux.target = "_blank";
                      aAux.textContent = data[i].Mensaje.replace(/((\/[_a-zA-Z0-9]+){0,}\/)([a-zA-Z0-9\s\.ñ\(\)]+)/, '$3');
                      newDiv1_2_2.appendChild(aAux);
                      break;

                    default:
                  }





                  newDiv1_2_3.className = "row right blue-grey-text text-lighten-2";
                  newDiv1_2_3.textContent = data[i].Hora;
                  newDiv1_1.appendChild(newDiv1_2_1);
                  newDiv1_1.appendChild(newDiv1_2_2);
                  newDiv1_1.appendChild(newDiv1_2_3);
                }


                newDiv1.appendChild(newDiv1_1);
                newDiv1.appendChild(newDiv1_2);


                if (typeof data[i].DiaNuevo != "undefined" && data[i].DiaNuevo != null) {
                  var newDivDia = document.createElement("div");
                  newDivDia.className = "row center";
                  var spanDivDia = document.createElement("span");
                  spanDivDia.className = "blue-grey-text text-lighten-1";
                  spanDivDia.textContent = data[i].DiaNuevo;

                  newDivDia.appendChild(spanDivDia);
                  newLi.appendChild(newDivDia);
                }
                newLi.appendChild(newDiv1);

                chat_Caja.appendChild(newLi);
              }


              if (data.length > numMensaje) {
                //Ajustar ScrollTop
                document.getElementById('Id_Caja_Grande').scrollTop = chat_Caja.scrollHeight;
              }


              numMensaje = data.length;

              //if (globalScrollTop != chat_Caja.scrollHeight) {
              //  document.getElementById('Id_Caja_Grande').scrollTop = chat_Caja.scrollHeight;
              //  globalScrollTop = chat_Caja.scrollHeight;
              //}

              //console.log("Se esta ejecutando Mensajes");
            }
          } else {
            if (data.startsWith("Error")) {} else if (data == "Fatal Error") {
              window.location.replace("<?php echo $this->url->get('Grupo/index/#'); ?>");
            }
          } 
        });

      }



      window.setInterval(function() {
        ajaxFuncion();
      }, 1500);
      
    </script>



    <script type="text/javascript">
      $(document).ready(function() {

        $("#id_boton_mensaje").click(function() {
          var textMessage = document.getElementById('id_mensaje').value;
          $.ajax({
            url: "<?php echo $this->url->get('Grupo/enviarMenAjax'); ?>",
            type: 'GET',
            dataType: 'json',
            data: {
              mensaje_name: textMessage
            }
          }).done(function(data) {
            document.getElementById('id_mensaje').value = "";
            if (data == "Error") {

            }
          });
        });


        $("#formuFotoAjax").on("submit", function(e) {
          e.preventDefault();
          var formData = new FormData(document.getElementById("formuFotoAjax"));

          $.ajax({
            url: "<?php echo $this->url->get('Grupo/enviarImgAjax'); ?>",
            type: "post",
            dataType: "json",
            data: formData,
            cache: false,
            contentType: false,
            processData: false
          }).done(function(data) {
            if (!Array.isArray(data)) {
              if (data.startsWith('Error')) {
                alert(data);
              } else {
                document.getElementById('id_path_foto').value = "";
                document.getElementById('id_error_img').textContent = "";
                borrarFotoField();
              }
            } else {
              var divErrorImg = document.getElementById('id_error_img');
              divErrorImg.textContent = "";
              for (var i = 0; i < data.length; i++) {
                var auxSpan = document.createElement('span');
                auxSpan.style.color = 'red';
                auxSpan.textContent = data[i];
                divErrorImg.appendChild(auxSpan);
              }
            }
          });
        });


        $("#formuDocAjax").on("submit", function(e) {
          e.preventDefault();
          var formData = new FormData(document.getElementById("formuDocAjax"));

          $.ajax({
            url: "<?php echo $this->url->get('Grupo/enviarDocAjax'); ?>",
            type: "post",
            dataType: "json",
            data: formData,
            cache: false,
            contentType: false,
            processData: false
          }).done(function(data) {
            if (!Array.isArray(data)) {
              if (data.startsWith('Error')) {
                alert(data);
              } else {
                document.getElementById('id_path_doc').value = "";
                document.getElementById('id_error_doc').textContent = "";
                borrarDocField();
              }
            } else {
              var divErrorDoc = document.getElementById('id_error_doc');
              divErrorDoc.textContent = "";
              for (var i = 0; i < data.length; i++) {
                var auxSpan = document.createElement('span');
                auxSpan.style.color = 'red';
                auxSpan.textContent = data[i];
                divErrorDoc.appendChild(auxSpan);
              }
            }
          });
        });

        $("#id_boton_history").click(function(){

            $.ajax({
                url: "<?php echo $this->url->get('Grupo/getHistoryAjax'); ?>",
                type: 'GET',
                dataType: 'json',
                data: {}
              }).done(function(data) {
                if(!((typeof data) == "string"))
                { 
                  var divHistory = document.getElementById("id_history_content");
                      divHistory.textContent = "";
                  for(var i=0;i<data.length; i++){
                    var auxP = document.createElement('p');
                    switch(data[i].Tipo_H){
                      case '0':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" se desconectó";
                      break;
                      case '1':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" se conectó";
                      break;
                      case '2':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" compartió una imagen al grupo";
                      break;
                      case '3':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" compartió un documento al grupo";
                      break;
                      case '4':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" cambió el nombre del grupo";
                      break;
                      case '5':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" cambió la contraseña del grupo";
                      break;
                      case '6':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" eliminó a alguien del grupo";
                      break;
                      case '7':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" se ha unido al grupo";
                      break;
                      case '8':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" ha salido del grupo";
                      break;
                      case '9':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" creó el grupo";
                      break;

                      case '10':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" compartió un enlace en el grupo";
                      break;
                      case '12':
                          auxP.textContent = data[i].Fecha+" ("+data[i].Hora+") - "+data[i].Nombre+" navegó por la biblioteca: "+data[i].Biblioteca;
                      break;

                      default: auxP.textContent = "Mensaje Dafault";
                    }
                    divHistory.appendChild(auxP);
                  }
                }
                else{
                  alert(data);
                }
              });
        });

        //$("#id_iFrame").on("load", function(e) {
            //var iFrame = document.getElementById('id_iFrame');
            //iFrame.contentDocument.body.addEventListener('mouseup', function(evt){
            //    alert("WORKS!!");
            //});
            //alert("Content: "+document.getElementById('id_iFrame').contentDocument);
        //});

      });
    </script>

    <script type="text/javascript">
      function checarEnterMensaje(evt) {
        if (evt.keyCode == 13 && !evt.shiftKey) {
          var textMessage = document.getElementById('id_mensaje').value;
          $.ajax({
            url: "<?php echo $this->url->get('Grupo/enviarMenAjax'); ?>",
            type: 'GET',
            dataType: 'json',
            data: {
              mensaje_name: textMessage
            }
          }).done(function(data) {
            document.getElementById('id_mensaje').value = "";
            if (data == "Error") {

            }
          });
        }

        tecla_final = String.fromCharCode(evt.keyCode);
        return tecla_final;
      }

      function recuperarChipInfo() {
        var infoChips = document.getElementById('ChipsPadre').getElementsByClassName('chip');
        var cadena = "[";

        for (var i = 0; i < infoChips.length; i++) {
          if (i == infoChips.length - 1) {
            cadena += "{\"tag\":\"" + infoChips[i].getElementsByClassName('chipMatricula')[0].textContent + "\"}]";
          } else {
            cadena += "{\"tag\":\"" + infoChips[i].getElementsByClassName('chipMatricula')[0].textContent + "\"},";
          }
        }
        document.getElementById('arrayChipPostId').value = cadena;

      }

    </script>
    <script type="text/javascript">
      function cambiarBiblioteca(){
        var bibliosImg = [ "acm.png",
                                      "ieee.png",
                                      "emerald.png",
                                      "emis.png",
                                      "nature.png",
                                      "acs.png",
                                      "springer.png",
                                      "tylor.png",
                                      "ams.png",
                                      "wiley.png"];
        //alert(bibliosImg[2]);
        var iframe = document.getElementById('id_iFrame');
        var optionSelected = document.getElementById('id_filtro_biblio').value;

        
        var url = "<?php echo $this->url->get('img/bibliotecas/');?>"+bibliosImg[optionSelected-1];
        document.getElementById('id_biblio_icon').src = url;
        document.getElementById('id_biblio_text').innerHTML = "Esta navegando por: "+document.getElementById('id_filtro_biblio')[optionSelected].text.bold();
        document.getElementById('id_biblio_div').style.display = 'block';
        switch(optionSelected){
          case '1':
              iframe.src = "https://www.proxydgb.buap.mx:2131/";
          break;
          case '2':
              iframe.src = "https://ieeexplore.ieee.org/Xplore/guesthome.jsp";
          break;
          case '3':
              iframe.src = "https://www.proxydgb.buap.mx:4420/insight/";
          break;
          case '4':
              iframe.src = "https://www.proxydgb.buap.mx:2247/php/dashboard?pc=MX";
          break;
          case '5':
              iframe.src = "http://www.proxydgb.buap.mx:2165/";
          break;
          case '6':
              iframe.src = "https://www.proxydgb.buap.mx:2100/";
          break;
          case '7':
              iframe.src = "https://www.proxydgb.buap.mx:2067/";
          break;
          case '8':
              iframe.src = "https://www.proxydgb.buap.mx:2071/";
          break;
          case '9':
              iframe.src = "https://www.proxydgb.buap.mx:2119/mathscinet/";
          break;
          case '10':
              iframe.src = "https://www.proxydgb.buap.mx:2175/";
          break;
        }

        //

        $.ajax({
                url: "<?php echo $this->url->get('Grupo/sendBiblioAjax'); ?>",
                type: 'POST',
                dataType: 'json',
                data: {biblio: optionSelected}
              }).done(function(data) {
                //alert("Respuesta: "+data);
              });
        

      }
    </script>

    <script type="text/javascript">
      var body = document.querySelector('body');

      body.onLoad = ajaxFuncion();
    </script>